services:
  - type: web
    name: nitter
    env: docker
    repo: https://github.com/rekker22/nitter
    plan: free
    autoDeploy: false
    healthCheckPath: /Jack/status/20
    envVars:
      - key: NITTER_CONFIG
        value: /src/nitter.conf
      - key: REDIS_HOST
        value: 127.0.0.1:6379
