services:
  - type: web
    name: nitter
    env: docker
    repo: https://github.com/rekker22/nitter/
    branch: render-yaml
    dockerfilePath: ""
    image: zedeus/nitter:latest
    plan: free
    envVars:
      - key: NITTER_CONFIG
        value: /src/nitter.conf
    disk:
      name: config-files
      mountPath: /src
      sizeGB: 1
    autoDeploy: false
    healthCheckPath: /Jack/status/20
    envVars:
      - key: REDIS_HOST
        value: nitter-redis:6379

  - type: pserv
    name: nitter-redis
    env: docker
    image: redis:6-alpine
    plan: free
    disk:
      name: redis-data
      mountPath: /data
      sizeGB: 1
